baseURL: https://yorks0n.github.io/TRxiv2
languageCode: en-us
title: TRxiv2
theme: PaperMod

params:
    homeInfoParams:
        Title: Track Weekly Popular bioRxiv Papers
        Content: Presenting up to ten most popular bioRxiv papers of the week in each category. 
paginate: 50

module:
  mounts:
    - source: node_modules/bootstrap/dist/js/bootstrap.bundle.min.js
      target: assets/js/bootstrap.bundle.min.js